"""empty message

Revision ID: 0968da0531c5
Revises: 4f783bc3f6af
Create Date: 2024-06-07 10:03:44.108088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0968da0531c5'
down_revision = '4f783bc3f6af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_download_verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('select_payment_method', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('receipt_file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_download_verification', schema=None) as batch_op:
        batch_op.drop_column('receipt_file_path')
        batch_op.drop_column('select_payment_method')

    # ### end Alembic commands ###
