"""empty message

Revision ID: 131cccfee0ab
Revises: db05eecefcaf
Create Date: 2024-05-06 08:48:24.828969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131cccfee0ab'
down_revision = 'db05eecefcaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('make_notification', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('make_notification', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
