"""empty message

Revision ID: 2e602539aaf2
Revises: eb50199ff364
Create Date: 2024-06-06 18:15:11.643852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e602539aaf2'
down_revision = 'eb50199ff364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('make_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('select_reason', sa.String(length=100), nullable=True),
    sa.Column('send_report_message', sa.String(length=255), nullable=True),
    sa.Column('is_check_by_admin', sa.Boolean(), nullable=True),
    sa.Column('received_report_message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('make_report')
    # ### end Alembic commands ###
