"""empty message

Revision ID: 4f783bc3f6af
Revises: 2e602539aaf2
Create Date: 2024-06-06 18:39:09.935018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f783bc3f6af'
down_revision = '2e602539aaf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('make_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('make_report', schema=None) as batch_op:
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
