"""empty message

Revision ID: 99180e2134c9
Revises: 114f43936a4a
Create Date: 2024-05-07 17:23:55.566114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99180e2134c9'
down_revision = '114f43936a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_product')
    with op.batch_alter_table('product_download_verification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('feedback_stars', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feedback_submitted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_download_verification', schema=None) as batch_op:
        batch_op.drop_column('feedback_submitted')
        batch_op.drop_column('feedback_stars')
        batch_op.drop_column('feedback_description')

    op.create_table('feedback_product',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('stars', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.cust_id'], name='feedback_product_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['products.p_id'], name='feedback_product_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
