"""empty message

Revision ID: 9fee2ce86d48
Revises: 
Create Date: 2024-06-10 11:33:24.597634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fee2ce86d48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_download_verification', schema=None) as batch_op:
        batch_op.alter_column('transaction_no',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.drop_index('transaction_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_download_verification', schema=None) as batch_op:
        batch_op.create_index('transaction_no', ['transaction_no'], unique=True)
        batch_op.alter_column('transaction_no',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
