"""empty message

Revision ID: b97ba5079591
Revises: 2251c8630750
Create Date: 2024-05-08 05:49:22.860628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b97ba5079591'
down_revision = '2251c8630750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cust_drop_address', sa.String(length=255), nullable=True))
        batch_op.drop_column('drop_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drop_address', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('cust_drop_address')

    # ### end Alembic commands ###
