"""empty message

Revision ID: e0e7044f8de1
Revises: b97ba5079591
Create Date: 2024-05-08 07:03:08.799686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0e7044f8de1'
down_revision = 'b97ba5079591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_boy_handover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cust_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('delivery_boy_handover_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['cust_id'], ['cust_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_boy_handover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('delivery_boy_handover_ibfk_2', 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('cust_id')

    # ### end Alembic commands ###
