"""empty message

Revision ID: eb50199ff364
Revises: 252a668a7130
Create Date: 2024-05-08 07:52:39.875812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb50199ff364'
down_revision = '252a668a7130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_boy_handover')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_boy_handover',
    sa.Column('ho_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('drop_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('cust_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cust_id'], ['customers.cust_id'], name='delivery_boy_handover_ibfk_2'),
    sa.ForeignKeyConstraint(['product_id'], ['products.p_id'], name='delivery_boy_handover_ibfk_1'),
    sa.PrimaryKeyConstraint('ho_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
