"""empty message

Revision ID: ef6dffba1f2d
Revises: 
Create Date: 2024-05-06 06:48:23.355172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6dffba1f2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('cust_user_name', sa.String(length=50), nullable=False),
    sa.Column('cust_full_name', sa.String(length=50), nullable=False),
    sa.Column('cust_phone', sa.String(length=50), nullable=False),
    sa.Column('cust_gender', sa.String(length=20), nullable=False),
    sa.Column('cust_rol_name', sa.String(length=20), nullable=False),
    sa.Column('cust_password', sa.String(length=256), nullable=False),
    sa.Column('cust_photo', sa.String(length=256), nullable=True),
    sa.Column('cust_registrationDate', sa.Date(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cust_id'),
    sa.UniqueConstraint('cust_phone'),
    sa.UniqueConstraint('cust_user_name')
    )
    op.create_table('product_category',
    sa.Column('pc_id', sa.Integer(), nullable=False),
    sa.Column('pc_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('pc_id'),
    sa.UniqueConstraint('pc_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('cnic', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('rol_name', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('photo', sa.String(length=256), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('registrationDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('cnic'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('make_notification',
    sa.Column('n_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notification_info', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_check_by_manager', sa.Boolean(), nullable=True),
    sa.Column('is_check_by_employee', sa.Boolean(), nullable=True),
    sa.Column('is_check_by_parent', sa.Boolean(), nullable=True),
    sa.Column('is_check_by_delivery_boy', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('n_id')
    )
    op.create_table('products',
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pc_id', sa.Integer(), nullable=False),
    sa.Column('p_name', sa.String(length=100), nullable=False),
    sa.Column('p_description', sa.Text(), nullable=True),
    sa.Column('p_price', sa.Numeric(precision=20, scale=1), nullable=False),
    sa.Column('p_image', sa.String(length=255), nullable=True),
    sa.Column('p_original_image', sa.String(length=255), nullable=True),
    sa.Column('p_isActive', sa.Boolean(), nullable=False),
    sa.Column('p_registrationDate', sa.DateTime(), nullable=False),
    sa.Column('p_stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pc_id'], ['product_category.pc_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('p_id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=1), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.cust_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.p_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_download_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('transaction_no', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.cust_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.p_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_download_verification')
    op.drop_table('order')
    op.drop_table('products')
    op.drop_table('make_notification')
    op.drop_table('users')
    op.drop_table('product_category')
    op.drop_table('customers')
    # ### end Alembic commands ###
